image: alpine:latest
pages:
  stage: deploy
  before_script:
    - npm -v
    - pm2 kill
    - pm2 status
  script:
    - cp -r -u * /var/www/bankexpo.uz
    - cd /var/www/bankexpo.uz
    - ls -la
    
    # - pm2 restart bankexpo
    - pm2 delete bankexpo
    # - NODE_OPTIONS="--max-old-space-size=1024" npm run i

    # - NODE_OPTIONS="--max-old-space-size=4096" npm run build
    # - pm2 restart bankexpo
    - PORT=3002 pm2 start dist/server/index.mjs --name bankexpo
  artifacts:
    paths:
      - ./*
  only:
    - main
